steps:

- id: 'Build Container Image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t' ,'${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA' , '-f' , 'Dockerfile' , '.' ]
  dir: "helloworld"
  
- id: 'Push Container Image SHORT_SHA'
  name: 'gcr.io/cloud-builders/docker:latest'
  args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA']

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  args: 
      [
        "deploy", "releases", "create", "release-$SHORT_SHA",
        "--delivery-pipeline", "cloud-run-pipeline",
        "--region", "${_LOCATION}",
        "--images", "app=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA"
      ]
  entrypoint: gcloud
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA'