apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-qa
  annotations:
    run.googleapis.com/client-name: gcloud
    client.knative.dev/user-image: australia-southeast1-docker.pkg.dev/hairhouse-379506/node-js-container/nodejs:6273526
    run.googleapis.com/client-version: 420.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    spec:
      containers:
      - image: app