apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: cloud-run-app
profiles:
- name: dev
  manifests:
    rawYaml:
    - dev.yaml
- name: qa
  manifests:
    rawYaml:
    - qa.yaml
- name: prod
  manifests:
    rawYaml:
    - prod.yaml
deploy:
  cloudrun: {}